services:
    admin.controller.abstract_controller:
        abstract: true
        calls:
            - ['setContainer', ['@service_container']]
            - ['setSecurityContext', ['@security.authorization_checker']]

    admin.controller.article_content_image_controller:
        class: AdminBundle\Controller\ImageUploadController
        parent: admin.controller.abstract_controller
        arguments:
            - "%article_inline_image_dir%"
            - "@core.service.absolute_url_generator"
            - "@jms_serializer"

    admin.controller.events_controller:
        class: AdminBundle\Controller\AdminEventsController
        parent: admin.controller.abstract_controller
        arguments:
            - "@ro.service.event_service"
            - "@stof_doctrine_extensions.uploadable.manager"

    admin.controller.articles_controller:
        class: AdminBundle\Controller\AdminArticlesController
        parent: admin.controller.abstract_controller
        arguments:
            - "@ro.service.article_service"

    admin.controller.posters_controller:
        class: AdminBundle\Controller\AdminPostersController
        parent: admin.controller.abstract_controller
        arguments:
            - "@stof_doctrine_extensions.uploadable.manager"
            - "@ro.service.event_service"

    admin.controller.galleries_controller:
        class: AdminBundle\Controller\AdminGalleriesController
        parent: admin.controller.abstract_controller
        arguments:
            - "@ro.service.gallery_service"
            - "@stof_doctrine_extensions.uploadable.manager"
            - "%gallery_image_dir"

    admin.controller.video_playlists_controller:
        class: AdminBundle\Controller\AdminVideoPlaylistsController
        parent: admin.controller.abstract_controller
        arguments:
            - "@ro.service.video_playlist_service"

    admin.controller.scripts_controller:
        class: AdminBundle\Controller\AdminScriptsController
        parent: admin.controller.abstract_controller
        arguments:
            - "@ro.service.script_service"

    admin.controller.teamss_controller:
        class: AdminBundle\Controller\AdminTeamsController
        parent: admin.controller.abstract_controller
        arguments:
            - "@ro.service.team_service"
