services:
    admin.controller.abstract_controller:
        abstract: true
        calls:
            - ['setContainer', ['@service_container']]
            - ['setSecurityContext', ['@security.authorization_checker']]

    admin.controller.event_controller:
        class: AdminBundle\Controller\AdminEventsController
        parent: admin.controller.abstract_controller
        arguments:
            - "@ro.service.event_service"
            - "@stof_doctrine_extensions.uploadable.manager"
