imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: fos_user.yml }
    - { resource: fos_rest.yml }
    - { resource: liip_imagine.yml }
    - { resource: ivory_ck_editor.yml }

parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['bootstrap_3_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

assetic:
    debug:          '%kernel.debug%'
    use_controller: false
#    use_controller: '%kernel.debug%'
#    read_from: '@TemplateBundle/Resources/public/js'
#    write_to: '%kernel.root_dir%/../web/js'
    filters:
        cssrewrite: ~
    assets:
#        default:
#            inputs:
#                - '@TemplateBundle/Resources/public/js/1bf71be111189e76987a4bb9b3115cb7.ttf'
#                - '@TemplateBundle/Resources/public/js/e605f2f859072ed0443aeda5adec4181.ttf'
        font_1:
            inputs:
                - '@TemplateBundle/Resources/public/js/1bf71be111189e76987a4bb9b3115cb7.ttf'
            output: 'js/1bf71be111189e76987a4bb9b3115cb7.ttf'
        font_2:
            inputs:
                - '@TemplateBundle/Resources/public/js/e605f2f859072ed0443aeda5adec4181.ttf'
            output: 'js/e605f2f859072ed0443aeda5adec4181.ttf'

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            uploadable: true
            sluggable: true
    uploadable:
        default_file_path: "%kernel.root_dir%/../web/uploads"
