imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

nelmio_api_doc:
    sandbox:
        request_format:
            method: accept_header
            formats:
                mobile v1: application/json

fos_rest:
    param_fetcher_listener: force
    body_listener:
        enabled: true
        default_format: json
    exception:
        enabled: true
        codes:
            'Doctrine\ORM\EntityNotFoundException': HTTP_NOT_FOUND
            'Doctrine\ORM\NoResultException': HTTP_NOT_FOUND
    serializer:
        serialize_null: true
    view:
        serialize_null: true
        view_response_listener: true
#        exception_wrapper_handler: null
        mime_types:
            json:
                - application/json
        formats:
            json: true
            html: true
    format_listener:
        rules:
            - { path: '^/api/', priorities: [json], fallback_format: json }
            - { path: '^/', priorities: [html, json], fallback_format: html }

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
