fos_http_cache:
    cache_control:
#        defaults:
#            overwrite: true
#        rules:
#            -
#                match:
#                    path: ^/api/
#                headers:
#                    cache_control: { public: true, max_age: 8000, s_maxage: 8000 }
#                    etag: true
#                    vary: [Accept-Encoding, Accept-Language]
