fos_user:
    service:
        mailer: fos_user.mailer.noop
    db_driver: orm
    firewall_name: main
    user_class: CoreBundle\Entity\User
    from_email:
        address: dummy@address.com
        sender_name: Dummy
