fos_rest:
    param_fetcher_listener: force
    routing_loader:
        include_format: false
    body_listener:
        enabled: true
        default_format: json
    exception:
        enabled: true
        codes:
            'Doctrine\ORM\EntityNotFoundException': HTTP_NOT_FOUND
            'Doctrine\ORM\NoResultException': HTTP_NOT_FOUND
    serializer:
        serialize_null: true
    view:
        serialize_null: true
        view_response_listener: true
#        exception_wrapper_handler: null
        mime_types:
            json:
                - application/json
        formats:
            json: true
            html: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/', priorities: [json], fallback_format: json }
            - { path: '^/', priorities: [html, json], fallback_format: html }
