ivory_ck_editor:
    base_path: "bundles/admin/js/ckeditor"
    js_path: "bundles/admin/js/ckeditor/ckeditor.js"
    default_config: default
    configs:
        default:
            allowedContent: true
            filebrowserUploadRouteParameters: ~
            filebrowserBrowseRouteAbsolute: true
#            extraPlugins: 'lineutils,widgetselection,clipboard,dialogui,notificationaggregator,notification,filetools,widget,uploadwidget,imageupload'
            toolbar:
                - ['Bold', 'Italic', 'Underline', 'Strike', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', '-', 'NumberedList', 'BulletedList', '-' , 'Outdent', 'Indent', '-', 'TextColor', 'Styles', 'Format', 'FontSize', 'Maximize']
            uiColor: "#fcfcfc"
            height: 450
        article_config:
            allowedContent: true
            extraPlugins: 'videoembed,dragresize'
            imageUploadUrl: '/admin/article/image/upload'
            filebrowserUploadRouteParameters: ~
            filebrowserBrowseRouteAbsolute: true
#            extraPlugins: 'lineutils,widgetselection,clipboard,dialogui,notificationaggregator,notification,filetools,widget,uploadwidget,imageupload'
            toolbar:
                - ['Bold', 'Italic', 'Underline', 'Strike', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', '-', 'NumberedList', 'BulletedList', '-' , 'Outdent', 'Indent', '-', 'Image', 'VideoDetector', 'Link', 'Unlink', '-', 'TextColor', 'Styles', 'Format', 'FontSize', 'Maximize']
            uiColor: "#fcfcfc"
            height: 450
