ivory_ck_editor:
    default_config: article_config
    configs:
        article_config:
            toolbar:
                - ['Bold', 'Italic', 'Underline', 'Strike', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', '-', 'NumberedList', 'BulletedList', '-' , 'Outdent', 'Indent', '-', 'Link', 'Unlink', '-', 'Image', 'TextColor', 'Styles', 'Format', 'FontSize', 'Maximize', 'Source']
            uiColor: "#fcfcfc"
            height: 450
