liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.root_dir%/../web'
                cache_prefix: 'media/cache'

    loaders:
        default:
            filesystem:
                data_root: '%kernel.root_dir%/../web/'

    driver: gd
    cache:  default
    data_loader: default
    default_image: null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets:
        cache: ~

        event_thumb_small:
            quality: 50
            filters:
              upscale: { min: [80, 80] }
              thumbnail: { size: [80, 80], mode: outbound, position: center}

        event_thumb_medium:
            quality: 70
            filters:
              upscale: { min: [120, 120] }
              thumbnail: { size: [120, 120], mode: outbound, position: center}

        event_thumb_large:
            quality: 70
            filters:
              upscale: { min: [200, 200] }
              thumbnail: { size: [200, 200], mode: outbound, position: center}

        admin_gallery_thumb:
            quality: 65
            filters:
              thumbnail: { size: [250, 170], mode: inset, position: center}

        article_thumb_big:
            quality: 75
            filters:
                thumbnail: { size: [640, 360], mode: outbound, position: center}

        article_thumb_small:
            quality: 60
            filters:
                thumbnail: { size: [480, 270], mode: outbound, position: center}

        og_preview_image:
            quality: 80
            filters:
                upscale: { min: [1200, 630] }
                thumbnail: { size: [1200, 630], mode: outbound, position: center}

        gallery_thumb:
            quality: 60
            filters:
                thumbnail: { size: [600, 600], mode: inset, position: center}

        gallery_image_mobile:
            quality: 70
            filters:
                scale:
                    dim: [1200, 1200]
