liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.root_dir%/../web'
                cache_prefix: 'media/cache'

    loaders:
        default:
            filesystem:
                data_root: '%kernel.root_dir%/../web/'

    driver: gd
    cache:  default
    data_loader: default
    default_image: null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets:
        cache: ~

        event_thumb_small:
            quality: 50
            filters:
              upscale: { min: [80, 80] }
              thumbnail: { size: [80, 80], mode: outbound, position: center}

        event_thumb_medium:
            quality: 70
            filters:
              upscale: { min: [120, 120] }
              thumbnail: { size: [120, 120], mode: outbound, position: center}

        event_thumb_large:
            quality: 70
            filters:
              upscale: { min: [200, 200] }
              thumbnail: { size: [200, 200], mode: outbound, position: center}
