api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

ro:
    resource: "@RoBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
