api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

ro:
    resource: "@RoBundle/Controller/"
    type:     annotation
    prefix:   /

libs_routing:
    resource: "routing_libs.yml"

admin_routing:
    resource: "@RoBundle/Resources/config/admin_routing.yml"
