fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

ro:
    resource: "@RoBundle/Controller/"
    type:     annotation
