services:
    api.factory.meta_data_factory:
        class: ApiBundle\Factory\MetaDataFactory
        arguments: ['@core.service.image_resizer']

    api.factory.abstract_factory:
        abstract: true
        calls:
            - ['setMetaDataFactory', ['@api.factory.meta_data_factory']]
            - ['setAbsoluteUrlGenerator', ['@core.service.absolute_url_generator']]
            - ['setImageResizer', ['@core.service.image_resizer']]

    api.factory.article_data_factory:
        class: ApiBundle\Factory\ArticleDataFactory
        parent: api.factory.abstract_factory

    api.factory.event_data_factory:
        class: ApiBundle\Factory\EventDataFactory
        parent: api.factory.abstract_factory

    api.factory.track_data_factory:
        class: ApiBundle\Factory\TrackDataFactory
        parent: api.factory.abstract_factory

    api.factory.track_list_data_factory:
        class: ApiBundle\Factory\TrackListDataFactory
        parent: api.factory.abstract_factory
        arguments:
            - '@api.factory.track_data_factory'

    api.factory.article_list_item_data_factory:
        class: ApiBundle\Factory\ArticleListItemDataFactory
        parent: api.factory.abstract_factory

    api.factory.poster_data_factory:
        class: ApiBundle\Factory\PosterDataFactory
        parent: api.factory.abstract_factory

    api.factory.video_list_data_factory:
        class: ApiBundle\Factory\VideoListDataFactory
        parent: api.factory.abstract_factory

    api.factory.gallery_image_list_data_factory:
        class: ApiBundle\Factory\GalleryImageListDataFactory
        parent: api.factory.abstract_factory
