services:
    ro.form.type.upload_file:
        class: RoBundle\Form\Type\UploadFileType
        tags:
            - { name: form.type }

    ro.form.type.gender:
        class: RoBundle\Form\Type\EventType
        tags:
            - { name: form.type }

    ro.form.type.article:
        class: RoBundle\Form\Type\ArticleType
        tags:
            - { name: form.type }

    ro.form.type.video_playlist:
        class: RoBundle\Form\Type\VideoPlaylistType
        tags:
            - { name: form.type }

    ro.form.type.video:
        class: RoBundle\Form\Type\VideoType
        tags:
            - { name: form.type }
